### ISSUE TITLE
Cannot reopen roll call

### ISSUE THREAD

**Issue by celinecamacho** [dedis/student_21_pop#578]
### Description (Actual behavior)
Not possible to reopen a roll call.

### Expected behavior
Should be possible to reopen a roll call after closing it.

### How to reproduce
1. Create a LAO
2. Create and close a Roll Call 
3. Reopen Roll Call

##### Front-ends:
- Fe2-Android 

##### Back-ends:
- Be2-Scala

### Possible root cause
The issue seems to be a cast from ReopenRollCall to OpenRollCall.

### Logs
```
17:12:43.761 [pop-be2-inner-actor-system-akka.actor.default-dispatcher-6] DEBUG c.n.s.AdditionalPropertiesValidator - validate( {"message":{"message_id":"guF6Tuxw99guZ91SK31s5h8rKdHQoZLIENQ4I6wE6wI=","sender":"Xr-CuwnzPWTVYM6Ux_NT_GgkL4E8By3NSeN8JmSI4-E=","signature":"fN2OUYvitACw79_hxqXNGCEwXyqqlHbKXCPJO7X6tTbMsP9MWxKZHeEkoU-9C-RYYk44oNYl8HVDNaWdAV4zBA==","data":"eyJhY3Rpb24iOiJyZW9wZW4iLCJvcGVuZWRfYXQiOjE2MzY2NDcxNjMsIm9wZW5zIjoiR0ZURjJSRjlHcUJRcHRkODJac3Y5dWFkcW5iR3Ytd0JOcld0c2J1d055Zz0iLCJ1cGRhdGVfaWQiOiJhZVpYS2pnYVRLdkNHeTNHc1ZodGdjcmNNbmhfNmg3dVNHS3NwWkZYaEFrPSIsIm9iamVjdCI6InJvbGxfY2FsbCJ9","witness_signatures":[]},"channel":"/root/b0gXkHOJ43DSpuxMiXzWOCvUb-khqHqkxIbbKJVsiKM="}, {"jsonrpc":"2.0","method":"publish","params":{"message":{"message_id":"guF6Tuxw99guZ91SK31s5h8rKdHQoZLIENQ4I6wE6wI=","sender":"Xr-CuwnzPWTVYM6Ux_NT_GgkL4E8By3NSeN8JmSI4-E=","signature":"fN2OUYvitACw79_hxqXNGCEwXyqqlHbKXCPJO7X6tTbMsP9MWxKZHeEkoU-9C-RYYk44oNYl8HVDNaWdAV4zBA==","data":"eyJhY3Rpb24iOiJyZW9wZW4iLCJvcGVuZWRfYXQiOjE2MzY2NDcxNjMsIm9wZW5zIjoiR0ZURjJSRjlHcUJRcHRkODJac3Y5dWFkcW5iR3Ytd0JOcld0c2J1d055Zz0iLCJ1cGRhdGVfaWQiOiJhZVpYS2pnYVRLdkNHeTNHc1ZodGdjcmNNbmhfNmg3dVNHS3NwWkZYaEFrPSIsIm9iamVjdCI6InJvbGxfY2FsbCJ9","witness_signatures":[]},"channel":"/root/b0gXkHOJ43DSpuxMiXzWOCvUb-khqHqkxIbbKJVsiKM="},"id":18}, $.params)
17:12:43.774 [pop-be2-inner-actor-system-akka.actor.default-dispatcher-11] ERROR ch.epfl.pop.pubsub.ClientActor - >>> Actor Exception : Failure(java.lang.ClassCastException: class ch.epfl.pop.model.network.method.message.data.rollCall.ReopenRollCall cannot be cast to class ch.epfl.pop.model.network.method.message.data.rollCall.OpenRollCall (ch.epfl.pop.model.network.method.message.data.rollCall.ReopenRollCall and ch.epfl.pop.model.network.method.message.data.rollCall.OpenRollCall are in unnamed module of loader 'app'))class ch.epfl.pop.model.network.method.message.data.rollCall.ReopenRollCall cannot be cast to class ch.epfl.pop.model.network.method.message.data.rollCall.OpenRollCall (ch.epfl.pop.model.network.method.message.data.rollCall.ReopenRollCall and ch.epfl.pop.model.network.method.message.data.rollCall.OpenRollCall are in unnamed module of loader 'app')
java.lang.ClassCastException: class ch.epfl.pop.model.network.method.message.data.rollCall.ReopenRollCall cannot be cast to class ch.epfl.pop.model.network.method.message.data.rollCall.OpenRollCall (ch.epfl.pop.model.network.method.message.data.rollCall.ReopenRollCall and ch.epfl.pop.model.network.method.message.data.rollCall.OpenRollCall are in unnamed module of loader 'app')
	at ch.epfl.pop.pubsub.graph.validators.RollCallValidator$.validateOpenRollCall(RollCallValidator.scala:43)
	at ch.epfl.pop.pubsub.graph.validators.RollCallValidator$.validateReopenRollCall(RollCallValidator.scala:62)
```

**Comment by BadrTad** [comment]
The bug was fixed in commit `653f4c7106a3d3b706131aeb670d80a5278ff5b2`
